# Workshop: sentiment analysis

## Program

- What is natural language processing and what are classification tasks 😀
- NLP tasks

### Build a sentiment classifier
- Load and explore your data
- Text preprocessing
- Load a model in the code environment
- Step-by-step building a classifier with a pre-trained model
- Run classification task: sentiment analysis on a data sample

Other classification datasets for classification tasks:

- [Spam detection dataset](https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset)

- [Hate Speech ETHOS dataset](https://paperswithcode.com/dataset/ethos)

- [Fake News Seek Truth dataset](https://www.kaggle.com/datasets/paulinepeps/truth-seeker-dataset-2023-truthseeker2023)

Some NLP tasks applied to cybersecurity:

- Named Entity Recognition (NER): Identifying entities such as names, locations, organizations, and dates. [CyNER](https://github.com/aiforsec/CyNER)

- Topic Modeling: Discovering hidden topics and themes in large datasets. [BERT Topic](https://maartengr.github.io/BERTopic/getting_started/quickstart/quickstart.html)

Libraries we use:

- [Transformers](https://huggingface.co/docs/transformers/index)

- [Datasets](https://huggingface.co/docs/datasets/index)

- [Torch](https://pytorch.org/)

In [1]:
!pip install transformers datasets -q

In [2]:
'''
We import transformers pipeline and torch
'''

from transformers import pipeline
import torch
from pprint import pprint


## Natural language processing tasks

### An example of previous generation of language model GPT-2

In [3]:
'''
Here we create our first pipeline with the library transformers
'''

from transformers import set_seed
generator = pipeline('text-generation', model='gpt2', clean_up_tokenization_spaces=True)

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [4]:
generator("I am a unicorn in a financial office,", max_length=20, truncation=True, num_return_sequences=5)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': 'I am a unicorn in a financial office, but I will make a profit out of writing articles."'},
 {'generated_text': "I am a unicorn in a financial office, if someone wants to help but don't even know where"},
 {'generated_text': 'I am a unicorn in a financial office, right on the ground floor. Do I have to pay'},
 {'generated_text': 'I am a unicorn in a financial office, and I am the only one to succeed. Please consider'},
 {'generated_text': 'I am a unicorn in a financial office, not a nerd in a library room. As a self'}]

In [5]:
generator("To bake cookies I need,", max_length=25, num_return_sequences=2, truncation=True)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': 'To bake cookies I need, so I know where to get one (no credit card is required). I find that, using'},
 {'generated_text': "To bake cookies I need, you don't need to remember. Use a little extra flour to keep them warm.\n\n"}]

In [6]:
generator("I don't like cats,", max_length=20, num_return_sequences=5, truncation=True)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': "I don't like cats, but if I was one of those people that has really gone off on"},
 {'generated_text': 'I don\'t like cats, I see in cats, there\'s a great life they go through."'},
 {'generated_text': 'I don\'t like cats, I don\'t like animals," he added, "and if you can'},
 {'generated_text': "I don't like cats, but I love dogs. It's kind of scary.\n\nSo"},
 {'generated_text': 'I don\'t like cats, but I know you\'ve had one recently," she added. "So'}]

In [7]:
#generator("...", max_length=.., num_return_sequences=..)

In [8]:
#generator()

### Labeling

In [9]:
from transformers import pipeline

classifier_labels = pipeline(model="facebook/bart-large-mnli")

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [10]:
results = classifier_labels(
    "I have a problem with my iphone that needs to be resolved !!",
    candidate_labels=["urgent", "not urgent", "phone", "tablet", "computer"],
)

for i, score in enumerate(results['scores']):
  results['scores'][i] = round(score, 2)

In [11]:
results

{'sequence': 'I have a problem with my iphone that needs to be resolved !!',
 'labels': ['phone', 'urgent', 'computer', 'tablet', 'not urgent'],
 'scores': [0.74, 0.23, 0.03, 0.0, 0.0]}

In [12]:
#change the sentence and print the results:

## Build a sentiment analysis classifier

### Instantiate a pipeline

In [13]:
from transformers import pipeline

classifier_sentiments = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

### Run the classifier

In [14]:
results = classifier_sentiments(["This is cool","This is not that cool", "This is bad"])
for result in results:
    result['raw'] = result['score']
    result['score'] = round(result['score'], 2)
results

[{'label': 'POSITIVE', 'score': 1.0, 'raw': 0.9998584985733032},
 {'label': 'NEGATIVE', 'score': 1.0, 'raw': 0.9997523427009583},
 {'label': 'NEGATIVE', 'score': 1.0, 'raw': 0.9997872710227966}]

### Many models for sentiment classification

By default transformers library uses a DistilBERT model for the pipelines we have created. Other models are available for the same type of task:

- [Roberta sentiment](https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest)

- [BERT base personality](https://huggingface.co/Minej/bert-base-personality)

Next, let's import this model into our code:

## Tokenizer

### What is a tokenizer

- Tokenization is the process of breaking down text into smaller **units** called **tokens**. In order to process text the computer needs first to transform it into numbers.

- Tokens are the basic building blocks used by Transformers models to understand and process text.

- Tokens can represent **words, subwords, or even individual characters**, depending on the model's vocabulary.

### Instanciate a tokenizer

The model we use is a [BERT](https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment)

In [15]:
from transformers import DistilBertTokenizer

model = "nlptown/bert-base-multilingual-uncased-sentiment"

tokenizer = DistilBertTokenizer.from_pretrained(model)

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'BertTokenizer'.
The class this function is called from is 'DistilBertTokenizer'.

We add our tokenizer to our pipeline:

In [16]:
new_classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

pytorch_model.bin:   0%|          | 0.00/669M [00:00<?, ?B/s]

In [17]:
new_classifier("I am happy")

[{'label': '5 stars', 'score': 0.5958592891693115}]


## Tokenization

A token is a value extracted from a **vocabulary list**.

A vocabulary list is a set words.

## Create tokens

### Split method

In [18]:
tokenized_text = "We are at a hacking conference.".split()
print(tokenized_text)

['We', 'are', 'at', 'a', 'hacking', 'conference.']

In [19]:
#tokenize another sentence with split method.

### Use a tokenizer

In [20]:
sequence = "We are at a hackish party."
tokens = tokenizer.tokenize(sequence)

print(tokens)

['we', 'are', 'at', 'a', 'hack', '##ish', 'party', '.']

In [21]:
#What is different?

In [22]:
#create a new sequence and generate tokens for this sequence

### Try another tokenizer

In [23]:
from transformers import XLNetTokenizer


another_tokenizer = XLNetTokenizer.from_pretrained("xlnet/xlnet-base-cased")
new_tokens = another_tokenizer.tokenize(sequence)

spiece.model:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.38M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/760 [00:00<?, ?B/s]

In [24]:
print(f"Tokens: {new_tokens}\n")

Tokens: ['▁We', '▁are', '▁at', '▁a', '▁hack', 'ish', '▁party', '.']

In [25]:
#What is different?

## Input IDs

Remember our sentence : "We are at a hacking conference." Let's see token ids for this sentence.

In [26]:
'''
Our current tokens:
Tokens: ['▁We', '▁are', '▁at', '▁a', '▁hacking', '_conference', '.']
'''

ids = tokenizer.convert_tokens_to_ids(tokens)

print(ids)

[11312, 10320, 10160, 143, 73961, 16551, 11727, 119]

In [27]:
# Tokenize another sentence and see the token ids:

# your_sentence = ""
# your_tokens =
# your_ids =

In [28]:
# @title
your_sentence = "We are at a hackers garden."
your_tokens = tokenizer.tokenize(your_sentence)
your_ids = tokenizer.convert_tokens_to_ids(your_tokens)

In [30]:
# @title
print(your_tokens)
print(your_ids)

['we', 'are', 'at', 'a', 'hacker', '##s', 'garden', '.']
[11312, 10320, 10160, 143, 84420, 10107, 15064, 119]

## Padding and truncation

Language models work with **tensors**, we need them to be **the same length**.

```
padding=True and truncation=True
```

In [31]:
sentences = ["A white poney.", "A white poney in the garden."]

batch = tokenizer(sentences, padding=True, truncation=True, max_length=512, return_tensors="pt") #pt for pyTorch

In [32]:
pprint(batch)

{'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]),
 'input_ids': tensor([[  101,   143, 11657, 53138, 10158,   119,   102,     0,     0,     0],
        [  101,   143, 11657, 53138, 10158, 10104, 10103, 15064,   119,   102]])}

In [33]:
#What are the ```'101'``` and ```'102'``` in the token list?

In [34]:
#what are the zeros?

In [35]:
#Try it out with two new sentences

Note it returns a dictionary with keys ```'input_ids'``` and ```'attention_mask'```, with two tensors the 'input ids' tensor and the 'attention_mask' tensor.
input_ids are unique ids.

# Dataset

We use the Dataset object from huggingface: https://huggingface.co/docs/datasets/v2.1.0/en/access

## Load a dataset from the hub

In [36]:
from datasets import load_dataset

dataset = load_dataset("carblacac/twitter-sentiment-analysis", split="train")

Downloading builder script:   0%|          | 0.00/4.38k [00:00<?, ?B/s]

Downloading metadata:   0%|          | 0.00/2.06k [00:00<?, ?B/s]

Downloading readme:   0%|          | 0.00/5.44k [00:00<?, ?B/s]

The repository for carblacac/twitter-sentiment-analysis contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/carblacac/twitter-sentiment-analysis.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N]  y

Downloading data:   0%|          | 0.00/5.38M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/2.23M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/149985 [00:00<?, ? examples/s]

Map:   0%|          | 0/61998 [00:00<?, ? examples/s]

Creating json from Arrow format:   0%|          | 0/120 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/30 [00:00<?, ?ba/s]

Creating json from Arrow format:   0%|          | 0/62 [00:00<?, ?ba/s]

Generating train split:   0%|          | 0/119988 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/29997 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/61998 [00:00<?, ? examples/s]

In [37]:
dataset

Dataset({
    features: ['text', 'feeling'],
    num_rows: 119988
})

The labels here are ```'feeling'``` let's change this for **sentiment**

In [38]:
# Rename the column
dataset = dataset.rename_column('feeling', 'sentiment')

# Verify the column has been renamed
pprint(dataset.features)

{'sentiment': Value(dtype='int32', id=None),
 'text': Value(dtype='string', id=None)}

In [39]:
# Explore the dataset
dataset[0]

{'text': '@fa6ami86 so happy that salman won.  btw the 14sec clip is truely a teaser',
 'sentiment': 0}

In [40]:
sample = dataset["text"][:10]
sample

['@fa6ami86 so happy that salman won.  btw the 14sec clip is truely a teaser',
 "@phantompoptart .......oops.... I guess I'm kinda out of it.... Blonde moment -blushes- epic fail",
 "@bradleyjp decidedly undecided. Depends on the situation. When I'm out with the people I'll be in Chicago with? Maybe.",
 '@Mountgrace lol i know! its so frustrating isnt it?!',
 "@kathystover Didn't go much of any where - Life took over for a while",
 '@TashaWilson like questions she asks me the date etc..i say that i have been to birmingham lol its weird o well  u ok?',
 "@lisastarlynn I haven't heard anything. I'll tweet you as soon as I hear. I'm really worried actually",
 '@SusanCosmos @speakgirl Thx 4 sharing!',
 '@lamere thank you so much, looking at these pics makes me want to have one more',
 'not it teh best form today, dont no why, just having a pissy day, i am all ways happy but to day ah not really   annoyed, bored, angry']

In [41]:
print(dataset.info)

DatasetInfo(description='The Twitter Sentiment Analysis Dataset contains 1,578,627 classified tweets, each row is marked as 1 for positive sentiment and 0 for negative sentiment.\nThe dataset is based on data from the following two sources:\n\nUniversity of Michigan Sentiment Analysis competition on Kaggle\nTwitter Sentiment Corpus by Niek Sanders\n\nFinally, I randomly selected a subset of them, applied a cleaning process, and divided them between the test and train subsets, keeping a balance between\nthe number of positive and negative tweets within each of these subsets.\n', citation='@InProceedings{thinknook:dataset,\ntitle = {Twitter Sentiment Analysis Training Corpus (Dataset)},\nauthor={Ibrahim Naji},\nyear={2012}\n}\n', homepage='https://raw.githubusercontent.com/cblancac/SentimentAnalysisBert/main', license='', features={'text': Value(dtype='string', id=None), 'sentiment': Value(dtype='int32', id=None)}, post_processed=None, supervised_keys=None, task_templates=None, builder_name='twitter-sentiment-analysis', dataset_name='twitter-sentiment-analysis', config_name='default', version=1.0.0, splits={'train': SplitInfo(name='train', num_bytes=9860675, num_examples=119988, shard_lengths=None, dataset_name='twitter-sentiment-analysis'), 'validation': SplitInfo(name='validation', num_bytes=2470008, num_examples=29997, shard_lengths=None, dataset_name='twitter-sentiment-analysis'), 'test': SplitInfo(name='test', num_bytes=5101825, num_examples=61998, shard_lengths=None, dataset_name='twitter-sentiment-analysis')}, download_checksums={'https://raw.githubusercontent.com/cblancac/SentimentAnalysisBert/main/data/train_150k.txt': {'num_bytes': 11697788, 'checksum': None}, 'https://raw.githubusercontent.com/cblancac/SentimentAnalysisBert/main/data/test_62k.txt': {'num_bytes': 4839762, 'checksum': None}}, download_size=16537550, post_processing_size=None, dataset_size=17432508, size_in_bytes=33970058)

In [42]:
print(dataset.features)

{'text': Value(dtype='string', id=None), 'sentiment': Value(dtype='int32', id=None)}

In [43]:
#How many tweets are in this dataset?
#What is the title of the dataset?
#When has it been published?

In [44]:
import pandas as pd

# Convert the dataset to a pandas DataFrame
df = pd.DataFrame(dataset)

# Display the columns of the DataFrame
print(df.columns)

Index(['text', 'sentiment'], dtype='object')

In [45]:
df['text'][0]

'@fa6ami86 so happy that salman won.  btw the 14sec clip is truely a teaser'

## Tokenize the dataset

In [46]:
tokenizer(dataset[0]["text"])

{'input_ids': [101, 137, 11403, 11325, 13736, 91958, 10297, 19308, 10203, 85111, 11441, 119, 48890, 10650, 10103, 10255, 10352, 10261, 38030, 10127, 16222, 10563, 143, 30082, 13377, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [47]:
def tokenization(example):
    return tokenizer(example["text"])

tokenized_dataset = dataset.map(tokenization, batched=True)

Map:   0%|          | 0/119988 [00:00<?, ? examples/s]

In [48]:
tokenized_dataset

Dataset({
    features: ['text', 'sentiment', 'input_ids', 'attention_mask'],
    num_rows: 119988
})

Now your set is ready for training!

## Create sample of the dataset

In [49]:
import pandas as pd

In [50]:
df = dataset.to_pandas()
sample = df.head(10)

In [51]:
sample

                                                text  sentiment
0  @fa6ami86 so happy that salman won.  btw the 1...          0
1  @phantompoptart .......oops.... I guess I'm ki...          0
2  @bradleyjp decidedly undecided. Depends on the...          1
3  @Mountgrace lol i know! its so frustrating isn...          1
4  @kathystover Didn't go much of any where - Lif...          1
5  @TashaWilson like questions she asks me the da...          1
6  @lisastarlynn I haven't heard anything. I'll t...          0
7             @SusanCosmos @speakgirl Thx 4 sharing!          1
8  @lamere thank you so much, looking at these pi...          0
9  not it teh best form today, dont no why, just ...          0

In [53]:
#Show the first 4 tweets of this dataframe

In [54]:
# @title
df[:4]

                                                text  sentiment
0  @fa6ami86 so happy that salman won.  btw the 1...          0
1  @phantompoptart .......oops.... I guess I'm ki...          0
2  @bradleyjp decidedly undecided. Depends on the...          1
3  @Mountgrace lol i know! its so frustrating isn...          1

In [55]:
#Show only the labels for the first 4 tweets

## Classify sentiment

![Pipeline](https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter2/full_nlp_pipeline.svg)

Source: HuggingFace NLP course

In [56]:
classifier = pipeline("sentiment-analysis")

def predict_sentiment(text):
  result = classifier(text)[0]
  return result['label']

sentiment = []
for text in sample['text']:
  sentiment.append(predict_sentiment(text))

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [62]:

sample['predicted_sentiment'] = sentiment
sample

/tmp/ipykernel_36/3544997318.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['predicted_sentiment'] = sentiment

,text,sentiment,predicted_sentiment
0,@fa6ami86 so happy that salman won. btw the 1...,0,POSITIVE
1,@phantompoptart .......oops.... I guess I'm ki...,0,NEGATIVE
2,@bradleyjp decidedly undecided. Depends on the...,1,NEGATIVE
3,@Mountgrace lol i know! its so frustrating isn...,1,NEGATIVE
4,@kathystover Didn't go much of any where - Lif...,1,NEGATIVE
5,@TashaWilson like questions she asks me the da...,1,POSITIVE
6,@lisastarlynn I haven't heard anything. I'll t...,0,NEGATIVE
7,@SusanCosmos @speakgirl Thx 4 sharing!,1,POSITIVE
8,"@lamere thank you so much, looking at these pi...",0,POSITIVE
9,"not it teh best form today, dont no why, just ...",0,NEGATIVE

In [58]:
# let's remap the labels to 0 for negative and 1 for positive:

# Define the mapping function
def map_sentiment(preds):
    return 1 if preds == "positive" else 0

for i in range(len(sample)):
    if sample.loc[i, 'predicted_sentiment'] == "POSITIVE":
        sample.loc[i, 'predicted_sentiment'] = 1
    else:
        sample.loc[i, 'predicted_sentiment'] = 0
        
# Use pprint to print the dataset features
sample

,text,sentiment,predicted_sentiment
0,@fa6ami86 so happy that salman won. btw the 1...,0,1
1,@phantompoptart .......oops.... I guess I'm ki...,0,0
2,@bradleyjp decidedly undecided. Depends on the...,1,0
3,@Mountgrace lol i know! its so frustrating isn...,1,0
4,@kathystover Didn't go much of any where - Lif...,1,0
5,@TashaWilson like questions she asks me the da...,1,1
6,@lisastarlynn I haven't heard anything. I'll t...,0,0
7,@SusanCosmos @speakgirl Thx 4 sharing!,1,1
8,"@lamere thank you so much, looking at these pi...",0,1
9,"not it teh best form today, dont no why, just ...",0,0

In [60]:
# Initialize counters
correct_predictions = 0
incorrect_predictions = 0

# compare predictions with actual labels
for i in range(len(sample)):
    if sample.loc[i, 'sentiment'] == sample.loc[i, 'predicted_sentiment']:
        correct_predictions += 1
    else:
        incorrect_predictions += 1

# Calculate percentages
total_predictions = correct_predictions + incorrect_predictions
correct_percentage = (correct_predictions / total_predictions) * 100
incorrect_percentage = (incorrect_predictions / total_predictions) * 100


# Print the results
print(f"Correct predictions: {correct_predictions}")
print(f"Incorrect predictions: {incorrect_predictions}")

Correct predictions: 5
Incorrect predictions: 5

# Thanks!

### Contact: [Twitter](www.twitter.com/hello_locked)  | [Mastdodon](https://infosec.exchange/deck/@C00kie_two)